# Generated by Django 3.1.2 on 2020-10-25 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carousel', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Images',
            new_name='ImagesCarousel',
        ),
    ]
