# Generated by Django 3.1.2 on 2020-10-19 08:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('description', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=60)),
                ('image', models.ImageField(upload_to='pet_imagen')),
            ],
        ),
        migrations.CreateModel(
            name='Shelter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('location', models.CharField(max_length=255)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('age', models.PositiveIntegerField(default=0)),
                ('sex', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Unknown', 'Unknown')], default='Unknown', max_length=10)),
                ('kind', models.CharField(choices=[('Cat', 'Cat'), ('Dog', 'Dog'), ('Other', 'Other')], default='Cat', max_length=5)),
                ('weight', models.PositiveIntegerField(default=0)),
                ('visits', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('Adoption', 'Adoption'), ('Adopted', 'Adopted')], default='Adoption', max_length=10)),
                ('color', models.CharField(choices=[('#fbfbfa', 'White'), ('000', 'Black'), ('#800000', 'Brown'), ('#808080', 'Gray')], default='FFF', max_length=7)),
                ('date_created', models.DateField(default=django.utils.timezone.now)),
                ('slug', models.SlugField(unique=True)),
                ('features', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='atributos', to='mainApp.feature')),
                ('images', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='mainApp.images')),
                ('shelter', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='albergue', to='mainApp.shelter')),
            ],
        ),
    ]
