# Generated by Django 3.1.2 on 2020-10-24 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='default',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pet',
            name='kind',
            field=models.CharField(choices=[('Cat', 'Cat'), ('Dog', 'Dog'), ('Guinea pig', 'Guinea pig'), ('Rabit', 'Rabit'), ('Other', 'Other')], default='Cat', max_length=10),
        ),
    ]
