# Generated by Django 3.1.2 on 2020-10-31 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shelter',
            name='about',
            field=models.TextField(blank=True, max_length=300),
        ),
    ]
