# Generated by Django 3.1.2 on 2020-10-19 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_auto_20201019_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shelter',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
