# Generated by Django 3.1.2 on 2020-10-31 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_auto_20201031_0940'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shelter',
            name='date_created',
        ),
    ]
