# Generated by Django 3.1.2 on 2020-10-19 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_auto_20201019_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='features',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='atributos', to='mainApp.feature'),
        ),
    ]
