# Generated by Django 3.1.2 on 2020-10-25 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_auto_20201024_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='shelter',
            name='image',
            field=models.ImageField(default='default_shetler.jpg', upload_to='shelter_imagen'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='kind',
            field=models.CharField(choices=[('Cat', 'Cat'), ('Dog', 'Dog'), ('Guinea pig', 'Guinea pig'), ('Rabbit', 'Rabbit'), ('Other', 'Other')], default='Cat', max_length=10),
        ),
    ]
