# Generated by Django 3.1.2 on 2020-10-31 09:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_remove_shelter_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='shelter',
            name='date_created',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
