# Generated by Django 3.1.2 on 2020-10-19 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0006_auto_20201019_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='about',
            field=models.CharField(default='description', max_length=300),
            preserve_default=False,
        ),
    ]
