# Generated by Django 3.1.2 on 2020-10-30 15:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0006_auto_20201025_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='shelter',
            name='date_created',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
