# Generated by Django 3.1.2 on 2020-10-22 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0007_pet_about'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='features',
        ),
        migrations.AddField(
            model_name='pet',
            name='features',
            field=models.ManyToManyField(blank=True, related_name='atributos', to='mainApp.Feature'),
        ),
        migrations.RemoveField(
            model_name='pet',
            name='images',
        ),
        migrations.AddField(
            model_name='pet',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='imagenes', to='mainApp.Images'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='status',
            field=models.CharField(choices=[('Adoption', 'Adoption'), ('Adopted', 'Adopted'), ('Urgent', 'Urgent')], default='Adoption', max_length=10),
        ),
        migrations.AlterField(
            model_name='shelter',
            name='slug',
            field=models.SlugField(blank='True', unique=True),
        ),
    ]
