# Generated by Django 3.1.2 on 2020-10-30 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0007_shelter_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shelter',
            name='about',
            field=models.TextField(default='Add something about your shelter', max_length=300),
        ),
    ]
