# Generated by Django 3.1.2 on 2020-10-31 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0008_auto_20201030_1727'),
        ('mainApp', '0004_shelter_date_created'),
    ]

    operations = [
    ]
