# Generated by Django 3.1.2 on 2020-10-31 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0009_merge_20201031_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shelter',
            name='about',
            field=models.TextField(max_length=300),
        ),
    ]
