# Generated by Django 3.1.2 on 2020-11-12 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0014_auto_20201107_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='color',
            field=models.CharField(choices=[('#fbfbfa', 'White'), ('#000', 'Black'), ('#800000', 'Brown'), ('#808080', 'Gray')], default='FFF', max_length=7),
        ),
    ]
