# Generated by Django 3.1.2 on 2020-11-12 18:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainApp', '0015_auto_20201112_1825'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(default=django.utils.timezone.now)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='pet_chatroom', to='mainApp.pet')),
                ('sender', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='sender_chatroom', to=settings.AUTH_USER_MODEL)),
                ('shelter', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='shelter_chatroom', to='mainApp.shelter')),
            ],
            options={
                'unique_together': {('shelter', 'sender', 'pet')},
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255)),
                ('read', models.BooleanField(default=False)),
                ('date_created', models.DateField(default=django.utils.timezone.now)),
                ('chatroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chatroom_Message', to='contactMessages.chatroom')),
                ('manager', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='manager_comment', to=settings.AUTH_USER_MODEL)),
                ('sender', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='sender_comment', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
