# Generated by Django 3.1.2 on 2020-11-12 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contactMessages', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='chatroom',
            unique_together=set(),
        ),
    ]
