# Generated by Django 3.1.2 on 2020-11-12 18:43

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainApp', '0015_auto_20201112_1825'),
        ('contactMessages', '0003_auto_20201112_1842'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='chatroom',
            unique_together={('shelter', 'sender', 'pet')},
        ),
    ]
