# Generated by Django 3.1.2 on 2020-11-12 18:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0015_auto_20201112_1825'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contactMessages', '0004_auto_20201112_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='sender_chatroom', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='shelter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='shelter_chatroom', to='mainApp.shelter'),
        ),
    ]
