# Generated by Django 3.1.2 on 2020-11-14 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactMessages', '0006_auto_20201112_1850'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='slug',
            field=models.SlugField(blank='True', unique=True),
        ),
    ]
