# Generated by Django 3.1.2 on 2020-11-18 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contactMessages', '0009_remove_message_receiver'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='read',
        ),
    ]
